# Generated by Django 4.2.3 on 2023-07-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='specialized',
        ),
    ]
