# Generated by Django 4.2.3 on 2023-07-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_remove_patients_specialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='specialized',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
