# Generated by Django 4.2.3 on 2023-07-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('dr_name', models.CharField(max_length=100)),
                ('specialized', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospital')),
            ],
        ),
    ]
