# Generated by Django 4.2.3 on 2023-07-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_doctors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
