# Generated by Django 4.2.3 on 2023-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_details_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='hospital_name',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
